name: planning_meeting
description: "An application to provide travel itineraries."

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.0
  flutter_markdown_plus: ^1.0.7
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^3.1.0
  cupertino_icons: ^1.0.8
  flutter_chat_core: ^2.0.0
  flutter_chat_ui: ^2.0.0
  kakao_map_sdk:
    git:
      url: 'https://github.com/gunyu1019/flutter_kakao_maps.git'
      ref: '8f483810e5db53c53c58e0572539a5c8c2fc5f41'

  # flutter_chat_ui
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/config/.env
    - assets/image/cafe.png
    - assets/image/food.png
    - assets/image/hotel.png
    - assets/image/shopping.png
    - assets/image/tourism.png

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
